apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-creds
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: 1m
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: grafana-admin-login
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: "grafana-admin-login"
      metadataPolicy: None
  - secretKey: grafana-admin-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: "grafana-admin-password"
      metadataPolicy: None