apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mc-copainsaulait
  namespace: mc-copainsaulait
spec:
  entryPoints:
    - minecraft
  routes:
    - kind: Rule
      match: Host(`*`)
      priority: 10
      services:
        - name: mc-copainsaulait-minecraft
          port: minecraft