apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mc-copainsaulait
  namespace: mc-copainsaulait
spec:
  entryPoints:
    - minecraft
  routes:
    - match: HostSNI(`*`)
      priority: 10
      services:
        - name: mc-copainsaulait-minecraft
          port: minecraft