apiVersion: v1
data:
  alertmanager.yaml: cm91dGU6CiAgcmVjZWl2ZXI6ICdkaXNjb3JkJwogIGdyb3VwX2J5OiBbJ2FsZXJ0bmFtZSddCiAgZ3JvdXBfd2FpdDogMzBzCiAgZ3JvdXBfaW50ZXJ2YWw6IDVtCiAgcmVwZWF0X2ludGVydmFsOiAzaAogIHJvdXRlczoKICAtIHJlY2VpdmVyOiAnZGlzY29yZCcKcmVjZWl2ZXJzOgotIG5hbWU6ICdkaXNjb3JkJwogIGRpc2NvcmRfY29uZmlnczoKICAtIHdlYmhvb2tfdXJsX2ZpbGU6IC9ldGMvYWxlcnRtYW5hZ2VyL3NlY3JldHMvYWxlcnRtYW5hZ2VyLXNlY3JldHMvZGlzY29yZC11cmw=
kind: Secret
metadata:
  name: alertmanager-config
type: Opaque