apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-config-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: alertmanager.yaml
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: "alertmanager-config"
      metadataPolicy: None