apiVersion: v2
name: kube-prometheus-stack
description: My personnal helm chart for kube-prometheus-stack
type: application
version: 75.15.1-6
appVersion: "v0.83.0"
dependencies:
- name: kube-prometheus-stack
  alias: prometheus-stack
  version: "79.12.0"
  repository: "https://prometheus-community.github.io/helm-charts"