minecraft:
  persistence:
    dataDir:
      enabled: true
      Size: 40Gi
  minecraftServer:
    type: "FABRIC"
    eula: true
    levelSeed: "100000019937711188"
    difficulty: "normal"
    ops: "SingeYaya,Anarchyz66,Bowsky33,GrosBoby"
    whitelist: "SingeYaya,Anarchyz66,Bowsky33,GrosBoby"
    motd: "Le serveur des copains au lait, Melvyn t'es pas le bienvenu"
    modrinth:
      projects: 
        - fabric-api
        - lithium
        - moogs-voyager-structures
        - inventory-sorting
      downloadDependencies: optional
    rcon:
      enabled: true 
      withGeneratedPassword: false 
      existingSecret: "rcon-password"
      secretKey: "rcon-password"
    spawnProtection: 0
  mcbackup:
    enabled: true
    backupName: "copainsaulait"
    linkLatest: "true"
    persistence:
      backupDir:
        enabled: true
        Size: 40Gi