minecraft:
  minecraftServer:
    type: "FABRIC"
    eula: true
  rcon:
    enabled: true 
    withGeneratedPassword: true 
  mcbackup:
    enabled: true
    backupName: "copainsaulait"
    linkLatest: "true"
    persistence:
      dataDir:
        enabled: true