minecraft:
  minecraftServer:
    type: "FABRIC"
    eula: true
    levelSeed: "100000019937711188"
    difficulty: "normal"
    ops: "SingeYaya"
    motd: "Le serveur des copains au lait, Melvyn t'es pas le bienvenu"
  persistence:
    dataDir:
      enabled: true
      Size: 40Gi
  rcon:
    enabled: true 
    withGeneratedPassword: true 
  mcbackup:
    enabled: true
    backupName: "copainsaulait"
    linkLatest: "true"
    persistence:
      backupDir:
        enabled: true
        Size: 40Gi