minecraft:
  minecraftServer:
    type: "FABRIC"
    eula: true
  persistence:
    dataDir:
      enabled: true
      Size: 40Gi
  rcon:
    enabled: true 
    withGeneratedPassword: true 
  mcbackup:
    enabled: true
    backupName: "copainsaulait"
    linkLatest: "true"
    persistence:
      backupDir:
        enabled: true
        Size: 40Gi
